import json, os
cx=lambda s:100+215*s
cy=lambda r:157+114*r
def N(i,t,l,sub,s,r): return {"id":i,"type":t,"label":l,"sublabel":sub,"stage":s,"row":r}
def H(a,b,l,v="emphasis",rev=False):
    f={"from":a,"to":b,"label":l,"route":"straight","fromSide":"left" if rev else "right","toSide":"right" if rev else "left"}
    if v!="default": f["variant"]=v
    return f
def V(a,b,l,s,r,v="emphasis",up=False):
    # between row r and r+1 in stage s
    f={"from":a,"to":b,"label":l,"route":"straight","fromSide":"top" if up else "bottom","toSide":"bottom" if up else "top","labelAt":[cx(s),cy(r)+57]}
    if v!="default": f["variant"]=v
    return f
def P(a,b,l,fs,ts,via,at,v="emphasis"):
    f={"from":a,"to":b,"label":l,"fromSide":fs,"toSide":ts,"via":via,"labelAt":at}
    if v!="default": f["variant"]=v
    return f
LEG={"entries":{"emphasis":{"label":"main path"},"default":{"label":"supporting input"},"dashed":{"label":"feedback"},"security":{"label":"caveat"},"database":{"label":"stored result"}}}
def D(slug,title,stages,nodes,flows,cards,h=520):
    for i,f in enumerate(flows): f["id"]="f%d"%i
    d={"schema_version":1,"diagram_type":"dataflow",
       "meta":{"title":title,"output":".archify/%s/%s.html"%(slug,slug),"quality_profile":"showcase","viewBox":[1080,h],"legend":LEG},
       "stages":[{"label":s} for s in stages],"nodes":nodes,"flows":flows,
       "cards":[{"dot":c[0],"title":c[1],"items":c[2]} for c in cards]}
    os.makedirs(".archify/"+slug,exist_ok=True)
    json.dump(d,open(".archify/%s/candidate.json"%slug,"w"),indent=1,ensure_ascii=False)

# ---------------- 001 Coral ----------------
D("001-coral-reef-tipping-points","Coral Reef Tipping Points: Model and Experiment Pipeline",
 ["Inputs","Model","Sweeps","Indicators","Findings"],
 [N("survey","external","Coral surveys","Scott Reef, 23 years",0,0),
  N("dhw","external","Heat stress","satellite DHW",0,1),
  N("mumby","external","Mean-field model","Mumby et al. 2007",0,2),
  N("abc","backend","ABC calibration","nudge switched off",1,0),
  N("potts","backend","Potts lattice","Metropolis, J / z",1,1),
  N("range","backend","Range switch","z = 0, 4, 8, 12, N",1,2),
  N("hyst","backend","Hysteresis ramp","dT up, then down",2,0),
  N("cusp","backend","Cusp sweep","dT x g, order tests",2,1),
  N("rate","backend","Ramp-rate test","sub-threshold end",2,2),
  N("width","database","Width W(z)","collapse vs recovery",3,0),
  N("ews","database","Early warnings","temporal, spatial",3,1),
  N("crit","database","Critical rate","r_c across seeds",3,2),
  N("f1","frontend","Range effect","vs mean field",4,0),
  N("f2","frontend","Lead times","by transition order",4,1),
  N("f3","frontend","Blind-spot test","warnings at R-tip",4,2)],
 [H("survey","abc","cover record","default"), H("dhw","potts","thermal forcing"), H("mumby","range","state structure","default"),
  V("abc","potts","parameters",1,0,"default"), V("range","potts","neighbourhood",1,1,"default",up=True),
  {**H("potts","cusp","dT, g grid"),"labelAt":[426,259]},
  P("potts","hyst","dT ramps","right","left",[[387,271],[387,157]],[400,214]),
  P("potts","rate","ramp rates","right","left",[[387,271],[387,385]],[404,328]),
  H("hyst","width","loops"), H("cusp","ews","snapshots"), H("rate","crit","tip or survive"),
  H("width","f1","W at each z"), H("ews","f2","trend onset"), H("crit","f3","R-tip runs")],
 [("emerald","Question",["Mumby, Hastings and Edwards (2007) found an irreversible grazing threshold in a model where every reef patch interacts with every other",
    "A Potts lattice is the same state structure with interactions restricted to neighbours",
    "The interaction range z is the experimental variable: how much hysteresis survives at short range, and does space give earlier warning"]),
  ("violet","Controls",["Coupling is divided by z, so range varies while total coupling is held fixed",
    "z = 0 (independent sites) must show no hysteresis",
    "All free-running results have the data-assimilation nudge switched off"]),
  ("slate","Methods and credit",["Survey data: Gilmour, Cook and Ryan (2021)",
    "Transition order from bimodality, the Binder cumulant and finite-size scaling",
    "Patch-size exponents by maximum likelihood (Clauset, Shalizi and Newman 2009); rate-induced tipping after Ashwin et al. (2012)"])])

# ---------------- 002 Olive ----------------
D("002-olive-grove-xylella","Olive Grove Xylella: Simulation and Percolation Pipeline",
 ["Sources","Simulation","Measured","Theory","Checks"],
 [N("paper","external","Fierro et al. 2019","lattice vector model",0,0),
  N("map","external","SIR-percolation","Grassberger, Newman",0,2),
  N("abm","backend","Grove simulation","256 trees, 3 years",1,0),
  N("log","database","Transmission log","source, target, day",1,1),
  N("front","backend","Front speed v","distance per day",2,0),
  N("T","backend","Transmissibility","T(d) by distance",2,1),
  N("stair","backend","Front timeline","quadratic, stepped",3,0),
  N("pc","backend","Bond percolation","threshold T_c",3,1),
  N("cmp","frontend","Curve overlay","theory vs simulated",4,0),
  N("size","frontend","Outbreak size","no simulation",4,1),
  N("space","frontend","Critical spacing","checked by one run",4,2)],
 [H("paper","abm","model rules","default"), V("abm","log","each infection",1,0),
  H("abm","front","front position"), H("log","T","infection pairs"),
  H("front","stair","speed v"), H("T","pc","T(d)"),
  P("map","pc","bond open with probability T","right","bottom",[[745,385]],[450,373],"default"),
  H("stair","cmp","predicted I(t)"), H("pc","size","cluster size"),
  P("pc","space","T = T_c","right","left",[[852,271],[852,385]],[852,328]),
  P("abm","cmp","simulated I(t)","top","top",[[315,112],[960,112]],[637,112],"default")],
 [("emerald","Source model",["Recreation of Fierro, Liccardo and Porcelli (2019), Scientific Reports: spittlebug vectors spreading Xylella fastidiosa through an olive grove",
    "The simulation logic is unchanged; a transmission log records which tree infected which"]),
  ("violet","Second route to the same answer",["The final infected set of a stochastic SIR epidemic is distributed as a bond-percolation cluster (Grassberger 1983; Newman 2002)",
    "Transmissibility T(d) is measured from one logged run, then outbreak size and the critical planting distance follow without simulating",
    "The predicted critical spacing is confirmed by a full simulation at that spacing"]),
  ("slate","What percolation cannot do",["Percolation describes the end state and has no clock",
    "The timeline comes from a front moving at constant speed, giving quadratic growth",
    "The annual vector reset turns that curve into a staircase"])])

# ---------------- 003 corrlib ----------------
D("003-corrlib-correlation-toolbox","corrlib: Correlation Toolbox Pipeline",
 ["Input","Measure and estimate","Matrix","Clean","Use"],
 [N("X","database","Data matrix X","variables x time",0,0),
  N("ticks","external","Tick data","irregular timestamps",0,1),
  N("meas","backend","Measures","Pearson, rank, tail",1,0),
  N("est","backend","Tick estimators","Hayashi-Yoshida",1,1),
  N("C","database","Correlation C","with q = N / T",2,1),
  N("epps","frontend","Epps curve","corr vs sampling",2,2),
  N("band","backend","Noise band","Marchenko-Pastur",3,0),
  N("clean","backend","Cleaners","clip, shrinkage",3,1),
  N("tyler","backend","Tyler estimator","heavy-tailed data",3,2),
  N("rank","frontend","Effective rank","independent modes",4,0),
  N("stack","backend","Optimal weights","MVDR = min variance",4,1),
  N("gain","frontend","Array gain","vs sqrt(N) line",4,2)],
 [H("X","meas","observations"), H("ticks","est","raw ticks"),
  P("meas","C","pairwise matrix","right","top",[[530,157]],[450,145]),
  H("est","C","synchronised"),
  P("est","epps","by sampling step","bottom","left",[[315,385]],[395,373],"default"),
  {**H("C","clean","C and q"),"labelAt":[632,259]},
  P("C","band","eigenvalues","right","left",[[602,271],[602,157]],[624,214],"default"),
  V("band","clean","band edges",3,0,"default"), V("tyler","clean","robust shape",3,1,"default",up=True),
  {**H("clean","stack","cleaned C"),"labelAt":[853,259]},
  P("clean","rank","spectrum","right","left",[[817,271],[817,157]],[830,214],"default"),
  V("stack","gain","stacked trace",4,1)],
 [("emerald","Four questions kept separate",["Which relationship is being measured: linear, rank, tail, lead-lag or partial",
    "How to estimate it from irregular ticks without the Epps bias",
    "How much of the matrix is noise, given q = variables / observations",
    "How to combine many sensors into one signal"]),
  ("violet","One formula in two fields",["Optimal array weights (Capon 1969) and minimum-variance portfolio weights (Markowitz 1952) are the same expression",
    "Diagonal loading in beamforming is linear shrinkage (Ledoit and Wolf 2004)",
    "The seismic denoiser and the Spanish solar project import these modules"]),
  ("slate","Credit",["Epps (1979); Hayashi and Yoshida (2005)",
    "Laloux, Cizeau, Bouchaud and Potters (1999); Bun, Bouchaud and Potters (2017)",
    "Tyler (1987); Frahm and Jaekel (2005)"])])

# ---------------- 004 Seismic ----------------
D("004-seismic-denoiser","Seismic Denoiser: Method Comparison Pipeline",
 ["Data","Methods","Detector","Scoreboard","Results"],
 [N("wave","external","SCEDC waveforms","noisy station-days",0,0),
  N("corr","external","corrlib","stacking, cleaning",0,1),
  N("cat","external","SCEDC catalogue","events and picks",0,2),
  N("single","backend","Single trace","raw and denoised",1,0),
  N("array","backend","Array stack","sum, MVDR, cleaned",1,1),
  N("pick","backend","STA/LTA picker","same threshold",2,0),
  N("score","database","Scoreboard","5 methods, one test",3,0),
  N("mc","frontend","Completeness Mc","Gutenberg-Richter",4,0),
  N("bias","frontend","Pick bias","early or late",4,1),
  N("cross","frontend","Crossover","by window length",4,2)],
 [H("wave","single","traces"), H("corr","array","weights","default"),
  H("single","pick","M1, M2"),
  P("array","pick","M3, M4, M5","right","bottom",[[530,271]],[450,259]),
  H("pick","score","picks"),
  P("cat","score","analyst picks, magnitudes","right","bottom",[[745,385]],[430,373],"default"),
  {**H("score","mc","detections"),"labelAt":[856,145]},
  P("score","bias","pick errors","right","left",[[817,157],[817,271]],[862,259]),
  P("score","cross","by window","right","left",[[817,157],[817,385]],[862,373]),
  ],
 [("emerald","Two acts, one scoreboard",["Act 1: the field-standard STA/LTA detector on raw traces (M1) and on an imported denoiser (M2)",
    "Act 2: the array is stacked by delay-and-sum (M3), optimal weights (M4) and optimal weights with a cleaned covariance (M5)",
    "All five methods are scored identically"]),
  ("violet","Numbers reported",["Magnitude of completeness Mc, raw against denoised, with the b value as a check that new detections are real",
    "Pick-time bias and spread against analyst picks",
    "The window length at which optimal weighting starts to beat plain averaging"]),
  ("slate","Credit",["Waveforms and catalogue: Southern California Earthquake Data Center",
    "STA/LTA: Allen (1978). Optimal array weights: Capon (1969)",
    "Imported denoiser: original authors to be credited once confirmed"])])

# ---------------- 005 Options ----------------
D("005-option-pricer","Option Pricer: Calibration, Solvers and Validation",
 ["Market","Extract","Pricers","Independent check","Evidence"],
 [N("spx","external","SPX chain","4 January 2023",0,0),
  N("set","external","SET50 chain","TFEX, European",0,1),
  N("par","backend","Put-call parity","forward, discount",1,0),
  N("sig","backend","sigma(t) curve","forward volatility",1,1),
  N("psor","backend","Projected SOR","American boundary",2,0),
  N("pde","backend","PDE solver","log-price grid, SOR",2,1),
  N("vec","backend","Vecer reduction","Asian, one dimension",2,2),
  N("tree","backend","Binomial tree","American benchmark",3,0),
  N("cf","backend","Closed form","integrated variance",3,1),
  N("mc","backend","Monte Carlo","control variate",3,2),
  N("bnd","frontend","Exercise boundary","on the value surface",4,0),
  N("conv","frontend","Convergence","order 2, fitted",4,1),
  N("agree","frontend","PDE vs MC","matching decimals",4,2)],
 [H("spx","par","quotes"), H("set","sig","ATM quotes","default"),
  V("par","sig","forwards",1,0), H("sig","pde","sigma(t)"),
  V("pde","psor","+ projection",2,0,up=True), V("pde","vec","new numeraire",2,1),
  H("psor","tree","American"), H("pde","cf","European"), H("vec","mc","Asian"),
  H("tree","bnd","agreement"), H("cf","conv","error by grid"), H("mc","agree","two methods")],
 [("emerald","One change to Black-Scholes",["Volatility becomes a function of time, read from the option chain as forward volatility",
    "European prices then depend only on the integrated variance, so an exact formula remains and the solver can be tested against it",
    "The implied interest rate recovered from put-call parity is checked against January 2023 rates"]),
  ("violet","Three option types",["European: validation of the solver, including measured convergence order",
    "American: free boundary by projected SOR, checked against a binomial tree",
    "Asian: reduction to one dimension by a change of numeraire, checked by Monte Carlo with a geometric control variate"]),
  ("slate","Credit and status",["Asian method: Vecer (2001), after Rogers and Shi (1995). Control variate: Kemna and Vorst (1990)",
    "Projected SOR as in Wilmott, Howison and Dewynne (1995)",
    "Built so far: SPX extraction, European and American pricing. Asian pricing and SET50 calibration are in progress"])])

# ---------------- 006 Italian power ----------------
D("006-italian-power-volatility","Italian Power Price Volatility: Forecasting Pipeline",
 ["Data","Features","Models","Out-of-sample test","Result"],
 [N("gme","external","GME prices","day-ahead, Italy",0,0),
  N("era","external","ERA5","observed weather",0,1),
  N("seas","external","SEAS5","25-member forecast",0,2),
  N("ret","backend","Daily returns","shared by all models",1,0),
  N("ext","backend","Extreme indices","monthly extremes",1,1),
  N("bc","backend","Bias correction","quantile mapping",1,2),
  N("n1","backend","GARCH(1,1)","null, no weather",2,0),
  N("n2","backend","GARCH-MIDAS","observed weather",2,1),
  N("n3","backend","Forecast MIDAS","SEAS5, plus regimes",2,2),
  N("score","database","Scoring","QLIKE, MSE, DM test",3,1),
  N("hor","frontend","Skill horizon","months of advantage",4,1)],
 [H("gme","ret","prices"), H("era","ext","daily fields"), H("seas","bc","forecast months","default"),
  V("ext","bc","ERA5 reference",1,1,"default"),
  H("ret","n1","returns"), H("ext","n2","tau drivers"), H("bc","n3","forecast tau"),
  H("n2","score","forecasts"),
  P("n1","score","baseline","right","top",[[745,157]],[665,145],"default"),
  P("n3","score","forecasts","right","bottom",[[745,385]],[665,373]),
  H("score","hor","skill by lead")],
 [("emerald","Replication, then one extension",["Replicates Guerzoni, Riso and Zoia (2026): extreme weather as the main driver of Italian electricity price volatility",
    "Extension: observed weather is replaced by SEAS5 seasonal forecasts made in advance, so the model can be used before the season happens"]),
  ("violet","Model",["GARCH-MIDAS (Engle, Ghysels and Sohn 2013): daily variance = slow level tau x fast GARCH component g",
    "tau is a beta-weighted average of past monthly weather extremes, set by two parameters",
    "A regime-switching layer is tested on the numbers and kept only if it improves the forecast"]),
  ("slate","The result is a horizon",["Three models are scored on the same out-of-sample window",
    "Expected outcome: forecast weather loses to observed weather and beats no weather",
    "The number reported is the forecast lead, in months, at which that advantage disappears"])])

# ---------------- 007 Spanish solar ----------------
D("007-spanish-solar-portfolio","Spanish Solar Portfolio: From Weather to Allocation",
 ["Data","Generation","Correlation","Structure","Strategy"],
 [N("era","external","ERA5 radiation","hourly, 20-40 sites",0,0),
  N("px","external","ENTSO-E prices","day-ahead, Spain",0,2),
  N("pv","backend","Panel model","deliberately simple",1,0),
  N("anom","backend","Clear-sky removal","deviations only",1,1),
  N("L","backend","Decay length L","rho(d) by season",2,0),
  N("C","database","Site matrix","cleaned with corrlib",2,1),
  N("neff","backend","Effective rank","raw vs cleaned",3,0),
  N("load","backend","Site loadings","on the shared mode",3,1),
  N("cap","backend","Capture rate","output-weighted",3,2),
  N("alloc","backend","Allocation","arms A1 to A5",4,1),
  N("score","frontend","Scoreboard","revenue, worst year",4,2)],
 [H("era","pv","irradiance"), V("pv","anom","site output",1,0), H("anom","C","deviations"),
  V("C","L","pairs by distance",2,0,"default",up=True),
  {**H("C","load","top mode"),"labelAt":[635,259]},
  P("C","neff","spectrum","right","left",[[602,271],[602,157]],[615,214]),
  H("px","cap","hourly prices","default"),
  H("load","alloc","exposures"),
  P("neff","alloc","N_eff floor","right","top",[[960,157]],[880,145],"default"),
  H("cap","score","capture"), V("alloc","score","weights",4,1)],
 [("emerald","The chain",["Spatial correlation leads to simultaneous generation, which depresses the price, which lowers the capture rate and revenue",
    "Correlation is computed on deviations from the clear-sky profile; raw output correlates near 0.95 only because the sun rises everywhere",
    "The decay length L is estimated by season: diversification is expected to fail under winter blocking highs"]),
  ("violet","Strategy",["Capacity shares from the cleaned covariance, with expected capture rate in place of expected return",
    "Five arms scored identically, from equal weight to the capture-rate objective",
    "Equal weight is expected to be competitive and is reported as such"]),
  ("slate","Data and credit",["Weather: ERA5 (Hersbach et al. 2020), a reanalysis with known cloud biases. Prices: ENTSO-E",
    "Capture rate follows the value-factor framing of Hirth (2013)",
    "Cleaning, effective rank, tail dependence and loadings are imported from corrlib"])])
print("written")
