#-------- test_step0.py ----------------------------------------------------------------
# Step 0 as tests: the solver against problems with known answers. Runs in seconds on the
# land-cover map coarsened to 6 km, with no data beyond what is committed.
#
#   python -m pytest tests -q

import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, HERE)
from tmax1km import step0
from tmax1km.grid import Grid, block_mean
from tmax1km.pde import DaySystem, Params, misfit

STATIC = np.load(os.path.join(HERE, "data", "estimated", "static_1km.npz"))


def test_anchors_are_exact_and_parameters_recovered_when_the_physics_is_complete():
    # truth generated by the PDE with q = 0: the fit should find the parameters it was made with
    r = step0.run(STATIC, n_days=10, q_size=0.0, coarsen=6)
    assert r["anchor_gap"] < 1e-6
    assert r["rmse_fit"] < 1e-3
    np.testing.assert_allclose(r["fitted"].pack(), r["true"].pack(), atol=0.05)          # within 5% in every parameter


def test_recovery_is_approximate_when_physics_is_missing():
    # truth has a q the fit does not know about: anchors still exact, parameters only roughly right
    r = step0.run(STATIC, n_days=12, q_size=0.3, coarsen=6)
    assert r["anchor_gap"] < 1e-6
    assert r["rmse_fit"] < r["rmse_start"]
    assert 0.6 < r["fitted"].tau_a / r["true"].tau_a < 1.6
    assert r["q_correlation"] > 0.8                                                      # q is recovered where stations can see


def test_adjoint_gradient_matches_finite_differences():
    rng = np.random.default_rng(1)
    grid = Grid().coarsen(10)
    frac = block_mean(STATIC["fractions"].astype(float), 10)
    days = step0.fake_days(grid, frac / frac.sum(0), 2, rng)
    cells = rng.choice(np.flatnonzero(grid.interior().ravel()), 15, replace=False)
    y = [30 + rng.normal(size=15) for _ in days]
    v = Params().pack()
    J, g = misfit(v, grid, frac, days, cells, y)
    for i in range(len(v)):
        e = np.zeros(len(v)); e[i] = 1e-5
        fd = (misfit(v + e, grid, frac, days, cells, y)[0] - misfit(v - e, grid, frac, days, cells, y)[0]) / 2e-5
        assert abs(g[i] - fd) < 1e-6 + 1e-4 * abs(fd)


def test_solution_never_overshoots_its_inputs():
    # with q = 0 the operator is monotone: theta stays between the extremes of theta_s and theta_E
    rng = np.random.default_rng(2)
    grid = Grid().coarsen(10)
    frac = block_mean(STATIC["fractions"].astype(float), 10)
    f = step0.fake_days(grid, frac / frac.sum(0), 1, rng)[0]
    theta = DaySystem(grid, Params(), frac, f).theta()
    lo, hi = min(f["theta_s"].min(), f["theta_E"].min()), max(f["theta_s"].max(), f["theta_E"].max())
    assert lo - 1e-9 <= theta.min() and theta.max() <= hi + 1e-9
